// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-38hYWhrOyjHAbGv04kHK1FRhlml-j0A',
    appId: '1:302114861904:web:30443a9a3c94b9183c3255',
    messagingSenderId: '302114861904',
    projectId: 'araba-kiralama-final',
    authDomain: 'araba-kiralama-final.firebaseapp.com',
    storageBucket: 'araba-kiralama-final.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQIlXa9ptXs-AH2XCrRas09foa7LHrcnQ',
    appId: '1:302114861904:android:f6971aaa4ba6f5963c3255',
    messagingSenderId: '302114861904',
    projectId: 'araba-kiralama-final',
    storageBucket: 'araba-kiralama-final.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDg-3AEjAUXqfgzVmWYNt847o7Gf1nx1MQ',
    appId: '1:302114861904:ios:85be2ffa710cbe733c3255',
    messagingSenderId: '302114861904',
    projectId: 'araba-kiralama-final',
    storageBucket: 'araba-kiralama-final.appspot.com',
    iosClientId: '302114861904-govrm2p474ke28l7u1u07ve9ke9s5jqe.apps.googleusercontent.com',
    iosBundleId: 'com.example.arabakiralama',
  );
}
